### ISSUE TITLE
Use C# expression-bodied members to cleanup MVC controller code

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templates#316]
In the "StarterWeb" template's `HomeController.cs` file, there's not much to the `Index` and `Error` action methods. This would be a perfect opportunity to demonstrate the use of C# expression-bodied members. I see the benefits as two-fold:
1. It would raise awareness of a new language feature
2. It would cleanup the code a little bit

Here are the exact changes I'm proposing:

``` c#
public IActionResult Index() => View();
public IActionResult Error() => View();
```

If everyone is okay with this idea, I'll submit a PR for it.

**Comment by herecydev** [comment]
:+1:

**Comment by Eilon** [comment]
I would say it's a non-goal to use the project templates to raise awareness of new language features. Otherwise we'd fill up the templates with lots of new syntax to demo the features.

So the question really is whether the new code is cleaner or not and still is useful for the sake of the template.

One thing to keep in mind with the templates is that they sometimes have extra stuff in them because the idea is that the template is not already a finished application. Rather, it is intended as a starting point that has a lot of details left to be filled in. Do we expect more code to be added to the `Index()` and `Error()` actions? I think for the `Index()` action the answer is definitely _yes_. So if it's changed to use an expression-bodied member, it becomes _more_ work for the user to convert it back to a method-bodied method (I just invented a new term :smile: ) so that the code can be added.

**Comment by scottaddie** [comment]
@Eilon Knowing that feature awareness isn't a goal of the templates, I do see your point with the `Index` action method. It likely will be modified by the developer. However, I would still argue that the default `Error` action method sees much more infrequent modification. What about applying the new syntax just to that method?

**Comment by Eilon** [comment]
For the `Error` method I could see it either way, no strong opinion from me. The new templates (as of RC1) do already have an expression-bodied member in them: https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/AI/NoAuth/Startup.cs#L74

So, flip a coin perhaps :smile:

**Comment by rustd** [comment]
I don't think we should change the Error method. If the user wants to modify the method, this pattern makes it harder. This pattern makes it harder to customize the code. In the Startup.cs chances are they will not modify it so it is fine to have it but IMO the Error method is something that should be easy to customize.

**Comment by rustd** [comment]
@scottaddie I am closing this issue as a Won't Fix.
