### ISSUE TITLE
UseDeveloperExceptionPage should be called first

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Templates#387]
Todays Entropy sample was throwing a 500 with no information. The following line was throwing

```
if (env.IsDevelopment())
{
    app.UseBrowserLink();            // throws 
    app.UseDeveloperExceptionPage();
    app.UseDatabaseErrorPage();
}
```

Moving  app.UseDeveloperExceptionPage(); up showed the problem. I could comment out browser link and work. If possible, move 

```
if (env.IsDevelopment()) 
```

to the top of the method and call UseDeveloperExceptionPage first. What if loggerFactory or UseApplicationInsightsRequestTelemetry throws?

**Comment by rustd** [comment]
This is a good suggestion. We should have the following order

``` C#
if (env.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
    app.UseDatabaseErrorPage();
    app.UseBrowserLink();
}
```

**Comment by Rick-Anderson** [comment]
Any chance you could move that block above the logging block - in case the logging block throws?

**Comment by Eilon** [comment]
Moving it above the logging block won't make any difference because those errors would occur _during startup_. Remember, this Startup code executes only _once_, and _before_ the first request (though it may very well be _triggered_ by the first request). But the middleware itself will run _during_ the first request. As such, the middleware cannot possibly catch a startup error.
