### ISSUE TITLE
Docker Web Application - Connection Reset by Peer

### ISSUE THREAD

**Issue by cmpadden** [aspnet/Templates#394]
It is not possible to access a Web Application running in Docker hosted on the Kestrel server with the default options; this is due to the Kestrel server defaulting to host on localhost opposed to 0.0.0.0. 

Replication can be done as follows:
1. Start by generating an ASP.NET Web API Application
2. Create a Docker image from the project scaffolding
`docker build -t aspnet-web-api .`
3. Run the Docker image
`docker run -t -d -p 80:5000 aspnet-web-api`
4. Attempt to send a request, and retrieve values
`curl localhost:80/api/values`
`curl: Recv failure: Connection reset by peer`

This issue can be resolved by adding the `--server.urls http://0.0.0.0:5000` flag to the Kestrel Server in the `project.json` file.

**Comment by rustd** [comment]
@glennc thoughts?

**Comment by glennc** [comment]
Yeah, this is a known thing. We used to allow public traffic when binding to localhost. However, this is not correct and makes it more difficult to secure Kestrel to just the machine.

So the default was changed so that if you are listening on localhost you can only receive local traffic. In the case of Docker you are browsing to it from a remote machine, so the traffic isn't local, and you need to listen on something other than localhost.

We will not be changing the logic in Kestrel, but all our Dockerfile samples and the VS Docker Tooling set the server.urls environment variable in the image so that it will listen appropriately. 

I don't think we should change the templates, having an app running on your dev machine be able to be accessed from other machines on the network shouldn't be the default behavior. We fix it in the places we can, wherever we have Docker templates, and I think that's enough.

Make sense?

**Comment by sayedihashimi** [comment]
It sounds like this is not a template issue so I'll close this now. If there is a template update needed please reopen.
