### ISSUE TITLE
DotNet build tools is not found

### ISSUE THREAD

**Issue by HalfLegend** [aspnet/Templates#427]
I could not create a project using the templates. Under MSBuild, the DOTNET and DOTNET.WEB build tools could not be found

**Comment by phenning** [comment]
@HalfLegend, unfortunately what you are seeing is because you do not have the latest Visual Studio Web tooling which is still under development. This repository feeds into that release and has dependencies in the project file which are introduced in the latest tooling. You should be able to take the template content though and be able to build using the dotnet cli.

**Comment by HalfLegend** [comment]
Thank you very much, I am expecting the new tools
