### ISSUE TITLE
Item templates have DNX branding

### ISSUE THREAD

**Issue by rustd** [aspnet/Templates#428]
Item templates should be using .NET Core instead of DNX
![dnx](https://cloud.githubusercontent.com/assets/1132652/13648261/9888b614-e5ec-11e5-92db-29d58a763e78.png)

**Comment by joeloff** [comment]
The DNX type is being shown because the PowerShell item templates are marked as applicable to all project types. The moment that you have item templates belonging to more than one project type, VS will automatically add the project type as a top level node.

Looks like PS has it's own project type but using the new appliesto markup that allows them to be shown in DNX project types.

**Comment by sayedihashimi** [comment]
@BillHiebert can we change the project type from "DNX" to ".NET Core"?

**Comment by phenning** [comment]
Fixed
