### ISSUE TITLE
Would you accept NancyFX templates?

### ISSUE THREAD

**Issue by jchannon** [aspnet/Templates#517]
Hi,

As a member of the Nancy team I think it would be awesome if VS shipped with some Nancy templates to give more exposure to the project and allow users to select WebAPI or Nancy for their project.  "It's all about the choice right?!".

Would you accept a PR with some Nancy templates that would then be shipped with VS?

Thanks

**Comment by sayedihashimi** [comment]
@jchannon thanks for the note here. To be honest with you, I'm really intrigued by this. I spent some time thinking about this. Below you'll find an answer to your direct question, and then after that where we may be able to go in the future.

We (_my team at least_) have never shipped any third party templates "in the box". I think that's for a number of reasons.
1. We would be obligated to support those templates just as we do ASP.NET templates today. For our customers who have support plans with Microsoft, if they find issues with the templates we provide, our support team will assist them. For a third party framework this is challenging not only because we would be on the hook for the support, but also it would be especially difficult because we don't have any internal NancyFx experts.
2. We would have to keep all the templates up to date at all times.
   To ship templates "in the box" is a lot of responsibility. For each release we update the templates, and during some releases there is significant churn (especially recently with .NET Core). Our current template infrastructure here is not helping that. With the way that templates work today we are spending a lot of time. The reason that we are not shipping a lot more templates is because its too difficult for us to author/maintain templates today. I'm currently working on a plan to improve this. More on this below.
3. Templates would have to support all options of the one asp.net dialog
   All the templates would have to support all the options from the one asp.net dialog. This may not seem challenging, but when the auth framework is being developed it's very difficult. Our template team often sits with the runtime and auth developers to get updated content in the templates.
4. Templates typically come in "hot" because they are the leaf node
   Templates are usually one of the last things that we finalize during a release. It's not unheard of to have significant template updates happening when the rest of the product is locked down. Because of this template updates near the end of the release requires careful coordination. Having this level of coordination with an external team would be challenging IMO.

### Possible future

In the future I'll be working with others on the story for `dotnet new`. Our **rough ideas** are to source templates from NuGet packages. (_FYI NuGet packages here may change, we are just now discussing with the NuGet team_) I'd like for the same templates that are installed with `dotnet new` to be available in the New Project Dialog of Visual Studio. Then we can build One ASP.NET on top of that. When we get there I think you'll find my team shipping templates in two ways
- "in the box", with `dotnet new` and Visual Studio
- in a gallery (maybe nuget.org not totally sure)

Then users would be able to install new templates in `dotnet new` with a command that pulls down the nuget package for the templates. The templates available "in the box" with `dotnet new` will be a pretty small number (~10 templates). Then users would install more specific templates after that.

Regarding the idea of not shipping any templates "in the box" and forcing users to install templates. When users install `dotnet new` or ASP.NET Tooling for Visual Studio there is a reasonable expectation to be able to get started right away. We also like to support the scenario where you install VS and then get on a plane and start coding. It would be bad if you had no templates to start with after installing VS in that case.

**Comment by thecodejunkie** [comment]
@sayedihashimi Hi, I know we've talked about templates before, albeit it was a couple of years ago and much might have changed since. The big problem with community templates have been, at least for us, the amount of manual work that goes into producing even a single template (talking about VS and not SideWaffle). Back when I last kept our templates relevant, these were the manual steps you had to do _for each template_ that you wanted to ship
1. Start Visual Studio and load the solution
2. `File -> Export Template`
3. Make sure "Project Template" is selected on the first page of the Wizard + select the correct project in the drop-down
4. Fill out template name, description, icon and preview image (either use the Browse button or copy/paste the path)
5. Export the template to the default (non-changeable) location
6. Go the output location
7. Break open the zip file
8. Open the `MyTemplate.vstemplate` file (yes, they all get this name when you export)
9. Modify the `DefaultName` element
10. Modify all `.cs` files and so that the namespace declarations (and other things you need to like assembly name etc) so it uses the `$safeprojectname$` placeholder
11. Insert the node (and sub-nodes), which contains information on which Nuget packages to install + versions
12. Zip up the content again (making sure you get the folder structure right)
13. Copy the zip to the right location in our VSIX project (`ProjectTemplates\CSharp\Web`)
14. Go back into visual studio, include the zip in the project, edit it's build action to "content" and configure it to be included in the VSI
15. We have to repeat these things for each and everyone of the templates we ship

There were zero chance of automating this, exporting multiple templates at once or anything like that in Visual Studio - has any of that changed yet? If you want to ship updated templates for when you put out a new package version, of your project, you soon loose your will to live.

Thanks

**Comment by sayedihashimi** [comment]
> The big problem with community templates have been, at least for us, the amount of manual work that goes into producing even a single template

Right. You're running into some of the same issues that we are. That's why I'm working to improve that.

@thecodejunkie I'm not aware of any significant changes to the current supported model for creating templates. This is not the right repo for feedback on the all up VS template experience. Here we're just covering ASP.NET/.NET Core templates. To make suggestions for VS all up you can file a new item at https://visualstudio.uservoice.com/.

With that said once we do our work I'm hoping that we can make it easier for people to create VS templates.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/aspnet/Templates/blob/dev/README.md.
