### ISSUE TITLE
Missing Location header within registration response.

### ISSUE THREAD

**Issue by JamieKeeling** [aspnet/Templates#576]
The **Verify_Account_Register_CreateAccount** Unit Test is failing due to a missing header within one of the responses.

An Assert has been configured which uses a local method to find the specified header from within a given HttpResponseHeaders object:

![image](https://cloud.githubusercontent.com/assets/7165035/15442990/a0b5128c-1edc-11e6-83bb-2fcfc1076b36.png)

In this instance, the unit test expects to find "Location" but it's not there, in turn generating a System.InvalidOperationException.

![image](https://cloud.githubusercontent.com/assets/7165035/15443107/9cb587ec-1edd-11e6-998f-35d481bbe985.png)

This was reproduced on a completely clean clone/build of the Templates based on the instructions followed [here](https://github.com/aspnet/Templates/wiki/Building-and-Running).

**Comment by phenning** [comment]
The InvalidOperation exception is being fixed.

One thing to keep in mind, that currently the Individual Authentication unit tests will only succeed if invoked through the command line build since the test\runtests.cmd script is responsible for running the database migration to create the database in dev mode.

**Comment by phenning** [comment]
4c29c026626dc2f7c8181202008ff288a6471ffb
