### ISSUE TITLE
Individual Auth ManageController should guard against null current user.

### ISSUE THREAD

**Issue by HaoK** [aspnet/Templates#596]
The various actions don't handle the situation where GetCurrentUser returns null very gracefully, we should add a check and show an error or just redirect back to Home or something in this situation instead.

**Comment by phenning** [comment]
@HaoK Looking at the linked issue, it looks like this was resolved in the runtime, Also, I'm unable to repro this with the current runtime and template bits. 

Do we have anything to do here? It looks like I'm always getting redirected to the login page when I try to navigate to the anything on the ManageController (due to the Authorize attribute on the controller) when I don't complete the external login flow.

**Comment by HaoK** [comment]
A runtime bug exposed the template bug, but basically we should check that user is not null consistently in all of the various actions before calling into the userManager:

https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Controllers/ManageController.cs#L53

Some do and some don't today
