### ISSUE TITLE
Remove unnecessary `imports` from project.json files

### ISSUE THREAD

**Issue by dougbu** [aspnet/Templates#613]
The templates still contain `imports` required only for earlier Json.NET releases.

@javiercn has cleaned up all of the runtime repos to remove these. But they remain in our templates.

This should be a candidate for the Preview 2 release.

**Comment by phenning** [comment]
It looks like we still need:
        "portable-net45+win8"
in the Individual Auth template due to Scaffolding due to Microsoft.Composition, this is needed both in the tool and at the project level.

We also still need all the imports for the BundleMinifier tool as well.

We can remove all the other imports from every other tool.

@Eilon, @DamianEdwards  Given this, do we want to keep the portable import at the project level for all templates for consistency.

**Comment by javiercn** [comment]
We have a bug for tracking Microsoft.Composition @pranavkm can you post it here for reference? I believe you filed it.

**Comment by Eilon** [comment]
My guess is that @DamianEdwards / @davidfowl would want to remove all unnecessary imports, but I'm not certain.

**Comment by pranavkm** [comment]
Microsoft.Composition work item: https://github.com/dotnet/corefx/issues/6598

**Comment by phenning** [comment]
N/A for msbuild based projects
