### ISSUE TITLE
Move "static void Main" from program.cs into startup.cs

### ISSUE THREAD

**Issue by madskristensen** [aspnet/Templates#689]
That allows us to remove _program.cs_ completely from the project templates and thereby reducing the number of files.

**Comment by peterblazejewicz** [comment]
But there was a reason why the MS folks opted for split the logic within app:
https://github.com/aspnet/Templates/issues/367#issue-124608144
I do sometimes merge files to have a single file - but that was purely for clean, _single file to run_ solution - [like here](https://github.com/aspnet/Hosting/tree/dev/samples/SampleStartups) - not necessary something I would usually.

**Comment by madskristensen** [comment]
For the vast majority of projects created in Visual Studio, having the startup/hosting logic in two separate files is just noise IMO.

**Comment by peterblazejewicz** [comment]
So Q.E.D. Thanks for discussion.

**Comment by madskristensen** [comment]
@phenning was this fixed?

**Comment by phenning** [comment]
@madskristensen actually, I think I closed the wrong issue

**Comment by phenning** [comment]
@madskristensen but looping back anyway, have we gotten any consensus whether we actually do want to do this?

@DamianEdwards @davidfowl

**Comment by davidfowl** [comment]
Yes, we want leave it as is.

**Comment by madskristensen** [comment]
@davidfowl What benefit does program.cs give to the average ASP.NET Core customer? To me it adds the noise of an extra file that is unlikely to ever be edited

**Comment by davidfowl** [comment]
There's a separation between the hosting code and program main. There are 2 separate wolds and should be treated as such. Services and configuration in the host don't flow to the application and merging the 2 things blurs that.

**Comment by madskristensen** [comment]
I understand the differences between the concerns of the two files, but what benefit does the user get? My argument is that while it might be more "correct" to keep 2 files, the noise added is worse than the "incorrectness" of combining them.

**Comment by leastprivilege** [comment]
Omg. Keep them separate of course.

**Comment by davidfowl** [comment]
@leastprivilege knows what's up 😄

**Comment by leastprivilege** [comment]
Let's also merge our HTML, CSS and js into a single file. Too much noise to have them separate ;)

**Comment by madskristensen** [comment]
@leastprivilege what do you think is the benefit of program.cs to the average ASP.NET Core customer?

**Comment by leastprivilege** [comment]
As David already said - there's a clear separation of concerns. 

Since you already said you understand that, I don't have to re-iterate. You seem to indicate that the "average" ASP.NET Core "customer" doesn't care.

Maybe we should stop dumbing down technology - with customers I guess you mean developers - we know what program.cs is and what static void main is as well. Nobody will be disturbed by an additional file at the root of the project where hosting concerns like command line params or other config is handled.

Removing such technical details behind magic extensions methods or by eliminating important application concerns just makes it harder to understand what's really going on. Especially for the "average customer".

I can't even believe that we even have this discussion.

**Comment by madskristensen** [comment]
This is a controversial subject and one that has been discussed before. I don't feel passionate enough about the issue to open another discussion on it at this time.

Closing the issue
